Repository open-company/open-company-lib, pull requests merged in 2018-11, with the labels that each got.

#39 Fix duplicated share
  project.clj
  src/oc/lib/api/common.clj
Labels: reviewing

#40 Add meta only if value supports it.
  src/oc/lib/api/common.clj
Labels: ready for deploy

#42 Pass in text with attachments
  project.clj
  src/oc/lib/slack.clj
Labels: ready for review

#43 Fix slugify issue when slug is sanitized to nothing. Test for the same.
  project.clj
  src/oc/lib/slugify.clj
  test/oc/unit/slugify.clj
Labels: reviewing
