Repository open-company/open-company-lib, pull requests merged in 2018-12, with the labels that each got.

#44 Fix change TTL
  project.clj
Labels: reviewing

#45 Auth lib
  src/oc/lib/auth.clj
Labels: ready for review

#47 Generate and decode a token that can be used to identify a user.
  project.clj
  src/oc/lib/api/common.clj
  src/oc/lib/jwt.clj
Labels: reviewing

#48 Post link behaviour
  project.clj
  src/oc/lib/api/common.clj
  src/oc/lib/jwt.clj
Labels: ready for deploy

#50 Fix decode id-token
  project.clj
  src/oc/lib/api/common.clj
Labels: ready for deploy
