Repository open-company/open-company-lib, pull requests merged in 2019-09, with the labels that each got.

#71 Move oauth state encoding/decoding utility functions into shared CLJC file
  project.clj
  src/oc/lib/oauth.cljc
Labels: reviewing

#72 Performance improvement
  project.clj
  src/oc/lib/async/watcher.clj
Labels: ready for use

#73 Decode :redirect key from oauth state string if present
  project.clj
  src/oc/lib/oauth.cljc
Labels: ready for review, reviewing
